version: '3'
services:
  reactor.db:
    image: mariadb:latest
    environment:
    - MYSQL_DATABASE=reactor
    - MYSQL_USER=reactor
    - MYSQL_PASSWORD=reactor
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
    - reactor.db:/var/lib/mysql
    ports:
    - "3306:3306"
  reactor.app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:80"
    links:
    - reactor.db

volumes:
  reactor.db:
    driver: local

